### ISSUE TITLE
永久链接中带有“{category}”按分类归档推送百度时链接错误

### ISSUE THREAD

**Issue by Sh1n3zZ** [ethanzhao2001/Sitemap-For-Typecho#5]
v1.3.3在提交百度收录时带有{category}按分类归档时仍会提交错误的链接，但在Sitemap中链接正常
![image](https://user-images.githubusercontent.com/110708622/209743880-dff8c770-0d1b-483e-86c8-435b4687d906.png)
![image](https://user-images.githubusercontent.com/110708622/209743941-55e042a1-04f0-42a6-8caf-833d6e500f2a.png)
![image](https://user-images.githubusercontent.com/110708622/209743955-e1d621d8-669b-4830-9197-7e7ed9379c24.png)

**Comment by ethanzhao2001** [comment]
已修复该问题，可更新使用，感谢您发现问题
